"""Public facade for subscription assembly and publication."""

from .contracts import (
    FinalizedSubscription,
    FinalizedSubscriptionDelete,
    PreparedSubscription,
    SubscriptionCandidate,
    SubscriptionDeleteKind,
    SubscriptionDeleteRequest,
    SubscriptionDeleteResult,
    SubscriptionError,
    SubscriptionInspectRequest,
    SubscriptionOutcome,
    SubscriptionPublishRequest,
    SubscriptionPublishResult,
    SubscriptionReconciliation,
    SubscriptionReconciliationItem,
    SubscriptionReconciliationStatus,
    SubscriptionRegistryEntry,
    SubscriptionRegistryState,
    SubscriptionServerArtifact,
    SubscriptionServerAvailability,
    SubscriptionServerSnapshot,
    SubscriptionSource,
    SubscriptionSourceFile,
)
from .publication import (
    NGINX_SUBSCRIPTIONS_CONTRACT_VERSION,
    REMOTE_SUBSCRIPTION_COMMAND,
    SshSubscriptionTransport,
    confirmed_subscription_url,
    parse_subscription_response,
    prepare_subscription,
    publish_prepared_subscription,
    render_remote_subscription_program,
)
from .reconciliation import (
    reconcile_subscription_server,
    reconcile_subscription_state,
)
from .registry import SUBSCRIPTION_REGISTRY_SCHEMA_VERSION, SubscriptionRegistry
from .server_management import (
    REMOTE_SUBSCRIPTION_MANAGEMENT_COMMAND,
    SshSubscriptionManagementTransport,
    delete_subscription,
    inspect_subscription_server,
    parse_subscription_delete_response,
    parse_subscription_inspection_response,
    render_remote_delete_program,
    render_remote_inspection_program,
)
from .sources import (
    collect_subscription_candidate,
    list_subscription_source_files,
    validate_subscription_name,
)

# Preserve the public runtime paths exposed by the former module while the
# implementation remains owned by focused package modules.
for _public_object in (
    SubscriptionError,
    SubscriptionSource,
    SubscriptionSourceFile,
    SubscriptionCandidate,
    SubscriptionRegistryEntry,
    SubscriptionPublishRequest,
    PreparedSubscription,
    SubscriptionPublishResult,
    FinalizedSubscription,
    SubscriptionServerArtifact,
    SubscriptionServerSnapshot,
    SubscriptionReconciliationItem,
    SubscriptionReconciliation,
    SubscriptionInspectRequest,
    SubscriptionDeleteRequest,
    SubscriptionDeleteResult,
    FinalizedSubscriptionDelete,
    SubscriptionRegistry,
    SshSubscriptionTransport,
    SshSubscriptionManagementTransport,
    validate_subscription_name,
    list_subscription_source_files,
    collect_subscription_candidate,
    render_remote_subscription_program,
    parse_subscription_response,
    prepare_subscription,
    confirmed_subscription_url,
    publish_prepared_subscription,
    render_remote_inspection_program,
    parse_subscription_inspection_response,
    inspect_subscription_server,
    render_remote_delete_program,
    parse_subscription_delete_response,
    delete_subscription,
    reconcile_subscription_state,
    reconcile_subscription_server,
):
    _public_object.__module__ = __name__
del _public_object

__all__ = (
    "SUBSCRIPTION_REGISTRY_SCHEMA_VERSION",
    "NGINX_SUBSCRIPTIONS_CONTRACT_VERSION",
    "REMOTE_SUBSCRIPTION_COMMAND",
    "REMOTE_SUBSCRIPTION_MANAGEMENT_COMMAND",
    "SubscriptionRegistryState",
    "SubscriptionOutcome",
    "SubscriptionDeleteKind",
    "SubscriptionServerAvailability",
    "SubscriptionReconciliationStatus",
    "SubscriptionError",
    "SubscriptionSource",
    "SubscriptionSourceFile",
    "SubscriptionCandidate",
    "SubscriptionRegistryEntry",
    "SubscriptionPublishRequest",
    "PreparedSubscription",
    "SubscriptionPublishResult",
    "FinalizedSubscription",
    "SubscriptionServerArtifact",
    "SubscriptionServerSnapshot",
    "SubscriptionReconciliationItem",
    "SubscriptionReconciliation",
    "SubscriptionInspectRequest",
    "SubscriptionDeleteRequest",
    "SubscriptionDeleteResult",
    "FinalizedSubscriptionDelete",
    "validate_subscription_name",
    "list_subscription_source_files",
    "collect_subscription_candidate",
    "SubscriptionRegistry",
    "SshSubscriptionTransport",
    "SshSubscriptionManagementTransport",
    "render_remote_subscription_program",
    "parse_subscription_response",
    "prepare_subscription",
    "confirmed_subscription_url",
    "publish_prepared_subscription",
    "render_remote_inspection_program",
    "parse_subscription_inspection_response",
    "inspect_subscription_server",
    "render_remote_delete_program",
    "parse_subscription_delete_response",
    "delete_subscription",
    "reconcile_subscription_state",
    "reconcile_subscription_server",
)
