from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

_CANONICAL_NAME_RE = re.compile(r"[-_.]+")
_LICENSE_NORMALIZATION = {
    "Apache 2.0": "Apache-2.0",
    "Apache License 2.0": "Apache-2.0",
}


def canonical_name(value: str) -> str:
    return _CANONICAL_NAME_RE.sub("-", value).lower()


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as source:
        value = json.load(source)
    if not isinstance(value, dict):
        raise TypeError(f"{path} must contain a JSON object")
    return value


def resolved_packages(report: dict[str, Any]) -> list[dict[str, Any]]:
    packages: list[dict[str, Any]] = []
    for item in report.get("install", []):
        metadata = item["metadata"]
        archive = item["download_info"]["archive_info"]
        sha256 = archive.get("hashes", {}).get("sha256")
        if not sha256:
            raise ValueError(f"missing SHA-256 for {metadata['name']}")
        url = item["download_info"]["url"]
        if not url.lower().endswith(".whl"):
            raise ValueError(f"non-wheel artifact selected for {metadata['name']}: {url}")
        declared_license = metadata.get("license_expression") or metadata.get("license")
        license_expression = _LICENSE_NORMALIZATION.get(
            declared_license, declared_license or "NOASSERTION"
        )
        packages.append(
            {
                "name": canonical_name(metadata["name"]),
                "version": metadata["version"],
                "sha256": sha256.lower(),
                "url": url,
                "license": license_expression,
                "requested": bool(item.get("requested")),
            }
        )
    packages.sort(key=lambda package: package["name"])
    if len({package["name"] for package in packages}) != len(packages):
        raise ValueError("resolved report contains duplicate canonical package names")
    return packages


def render_lock(packages: list[dict[str, Any]], report: dict[str, Any]) -> str:
    environment = report.get("environment", {})
    python_version = environment.get("python_full_version", "unknown")
    platform = environment.get("platform_system", "unknown")
    machine = environment.get("platform_machine", "unknown")
    lines = [
        "# Generated by supply_chain/generate.py from a pip --report resolution.",
        f"# Target: {platform} {machine}, CPython {python_version}.",
        "# Regenerate when requirements or the target Python/platform changes.",
        "--only-binary=:all:",
        "--require-hashes",
        "",
    ]
    for package in packages:
        lines.append(f"{package['name']}=={package['version']} --hash=sha256:{package['sha256']}")
    return "\n".join(lines) + "\n"


def python_component(package: dict[str, Any]) -> dict[str, Any]:
    if package["license"] == "NOASSERTION":
        raise ValueError(f"missing declared license for {package['name']}")
    purl = f"pkg:pypi/{package['name']}@{package['version']}"
    return {
        "type": "library",
        "bom-ref": purl,
        "name": package["name"],
        "version": package["version"],
        "purl": purl,
        "hashes": [{"alg": "SHA-256", "content": package["sha256"]}],
        "licenses": [{"expression": package["license"]}],
        "externalReferences": [{"type": "distribution", "url": package["url"]}],
        "properties": [
            {
                "name": "vpn-admin-panel:direct-requirement",
                "value": str(package["requested"]).lower(),
            }
        ],
    }


def asset_component(asset: dict[str, Any]) -> dict[str, Any]:
    artifact = asset["artifact"]
    source = asset["source"]
    license_info = asset["license"]
    properties = [
        {"name": "vpn-admin-panel:artifact-path", "value": artifact["path"]},
        {"name": "vpn-admin-panel:source-ref", "value": source["ref"]},
        {"name": "vpn-admin-panel:source-commit", "value": source["commit"]},
        {"name": "vpn-admin-panel:license-path", "value": license_info["path"]},
        {
            "name": "vpn-admin-panel:license-sha256",
            "value": license_info["sha256"],
        },
    ]
    if archive_sha256 := artifact.get("archive_sha256"):
        properties.append({"name": "vpn-admin-panel:archive-sha256", "value": archive_sha256})
    return {
        "type": "application",
        "bom-ref": asset["purl"],
        "name": asset["name"],
        "version": asset["version"],
        "purl": asset["purl"],
        "hashes": [{"alg": "SHA-256", "content": artifact["sha256"]}],
        "licenses": [{"expression": license_info["expression"]}],
        "externalReferences": [
            {"type": "distribution", "url": artifact["distribution_url"]},
            {"type": "vcs", "url": source["url"]},
            {"type": "license", "url": license_info["url"]},
        ],
        "properties": properties,
    }


def render_sbom(packages: list[dict[str, Any]], assets: dict[str, Any]) -> str:
    if assets.get("schema_version") != 1:
        raise ValueError("unsupported third-party asset inventory schema")
    components = [python_component(package) for package in packages]
    components.extend(asset_component(asset) for asset in assets.get("components", []))
    components.sort(key=lambda component: component["bom-ref"])
    document = {
        "$schema": "https://cyclonedx.org/schema/bom-1.6.schema.json",
        "bomFormat": "CycloneDX",
        "specVersion": "1.6",
        "version": 1,
        "metadata": {
            "component": {
                "type": "application",
                "bom-ref": "pkg:generic/vpn-admin-panel@0.0.0",
                "name": "vpn-admin-panel",
                "version": "0.0.0",
            }
        },
        "components": components,
    }
    return json.dumps(document, ensure_ascii=False, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a hash-locked requirements file and optional CycloneDX SBOM."
    )
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--lock", type=Path, required=True)
    parser.add_argument("--sbom", type=Path)
    parser.add_argument("--assets", type=Path)
    args = parser.parse_args()

    report = load_json(args.report)
    packages = resolved_packages(report)
    args.lock.write_text(render_lock(packages, report), encoding="utf-8", newline="\n")

    if bool(args.sbom) != bool(args.assets):
        parser.error("--sbom and --assets must be supplied together")
    if args.sbom is not None and args.assets is not None:
        assets = load_json(args.assets)
        args.sbom.write_text(render_sbom(packages, assets), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
