"""Public facade for fixed Management operations."""

from .base_security import (
    REMOTE_BASE_SECURITY_MANAGEMENT_SCRIPT,
    SshBaseSecurityManagementTransport,
    manage_base_security,
)
from .connection_validation import validate_connection_settings, validate_mieru_port
from .contracts import (
    BASE_SECURITY_ACTIONS,
    BASE_SECURITY_SERVICES,
    DOCKER_ACTIONS,
    HYSTERIA2_ACTIONS,
    MIERU_ACTIONS,
    NETDATA_ACTIONS,
    NGINX_ACTIONS,
    XRAY_ACTIONS,
    AllowedInboundPort,
    BaseSecurityAction,
    BaseSecurityManagementStatus,
    BaseSecurityService,
    DockerAction,
    DockerManagementStatus,
    Hysteria2ManagementStatus,
    ManagementMutationOutcome,
    ManagementMutationResult,
    MieruAction,
    MieruManagementStatus,
    NetdataAccessDetails,
    NetdataAction,
    NetdataManagementStatus,
    NginxAction,
    NginxManagementStatus,
    PublishedUdpPort,
    ServiceManagementStatus,
    XrayAction,
    XrayManagementStatus,
)
from .docker import (
    REMOTE_DOCKER_MANAGEMENT_SCRIPT,
    SshDockerManagementTransport,
    manage_docker,
)
from .errors import (
    ManagementError,
    ManagementIndeterminateError,
    ManagementLaunchError,
    ManagementRemoteRejectedError,
)
from .hysteria2 import (
    REMOTE_HYSTERIA2_CONNECTION_UPDATE_SCRIPT,
    REMOTE_HYSTERIA2_MANAGEMENT_SCRIPT,
    SshHysteria2ConnectionUpdateTransport,
    SshHysteria2ManagementTransport,
    manage_hysteria2,
    update_hysteria2_connection,
)
from .mieru import (
    REMOTE_MIERU_MANAGEMENT_SCRIPT,
    REMOTE_MIERU_PORT_UPDATE_SCRIPT,
    SshMieruManagementTransport,
    SshMieruPortUpdateTransport,
    manage_mieru,
    update_mieru_port,
)
from .netdata import (
    REMOTE_NETDATA_MANAGEMENT_SCRIPT,
    SshNetdataManagementTransport,
    manage_netdata,
)
from .netdata_credentials import load_netdata_access_details
from .nginx import (
    REMOTE_NGINX_MANAGEMENT_SCRIPT,
    SshNginxManagementTransport,
    manage_nginx,
)
from .reboot import SshServerRebootTransport, schedule_server_reboot
from .xray import (
    REMOTE_XRAY_CONNECTION_UPDATE_SCRIPT,
    REMOTE_XRAY_MANAGEMENT_SCRIPT,
    SshXrayConnectionUpdateTransport,
    SshXrayManagementTransport,
    manage_xray,
    update_xray_connection,
)

# Preserve public runtime paths from the former module for diagnostics and
# serialized references while keeping implementation ownership in submodules.
for _public_object in (
    ManagementError,
    ManagementLaunchError,
    ManagementRemoteRejectedError,
    ManagementIndeterminateError,
    ManagementMutationResult,
    PublishedUdpPort,
    DockerManagementStatus,
    SshDockerManagementTransport,
    SshServerRebootTransport,
    ServiceManagementStatus,
    NginxManagementStatus,
    SshNginxManagementTransport,
    NetdataManagementStatus,
    NetdataAccessDetails,
    SshNetdataManagementTransport,
    AllowedInboundPort,
    BaseSecurityManagementStatus,
    SshBaseSecurityManagementTransport,
    XrayManagementStatus,
    SshXrayManagementTransport,
    SshXrayConnectionUpdateTransport,
    Hysteria2ManagementStatus,
    SshHysteria2ManagementTransport,
    SshHysteria2ConnectionUpdateTransport,
    MieruManagementStatus,
    SshMieruManagementTransport,
    SshMieruPortUpdateTransport,
    manage_docker,
    schedule_server_reboot,
    manage_base_security,
    manage_nginx,
    load_netdata_access_details,
    manage_netdata,
    manage_xray,
    validate_connection_settings,
    update_xray_connection,
    manage_hysteria2,
    update_hysteria2_connection,
    manage_mieru,
    validate_mieru_port,
    update_mieru_port,
):
    _public_object.__module__ = __name__
del _public_object

__all__ = (
    "DockerAction",
    "DOCKER_ACTIONS",
    "XrayAction",
    "XRAY_ACTIONS",
    "HYSTERIA2_ACTIONS",
    "MieruAction",
    "MIERU_ACTIONS",
    "NginxAction",
    "NGINX_ACTIONS",
    "NetdataAction",
    "NETDATA_ACTIONS",
    "ManagementError",
    "ManagementLaunchError",
    "ManagementRemoteRejectedError",
    "ManagementIndeterminateError",
    "ManagementMutationOutcome",
    "ManagementMutationResult",
    "PublishedUdpPort",
    "DockerManagementStatus",
    "REMOTE_DOCKER_MANAGEMENT_SCRIPT",
    "SshDockerManagementTransport",
    "manage_docker",
    "SshServerRebootTransport",
    "schedule_server_reboot",
    "BaseSecurityService",
    "BaseSecurityAction",
    "BASE_SECURITY_SERVICES",
    "BASE_SECURITY_ACTIONS",
    "ServiceManagementStatus",
    "NginxManagementStatus",
    "REMOTE_NGINX_MANAGEMENT_SCRIPT",
    "SshNginxManagementTransport",
    "manage_nginx",
    "NetdataManagementStatus",
    "NetdataAccessDetails",
    "load_netdata_access_details",
    "REMOTE_NETDATA_MANAGEMENT_SCRIPT",
    "SshNetdataManagementTransport",
    "manage_netdata",
    "AllowedInboundPort",
    "BaseSecurityManagementStatus",
    "REMOTE_BASE_SECURITY_MANAGEMENT_SCRIPT",
    "SshBaseSecurityManagementTransport",
    "manage_base_security",
    "XrayManagementStatus",
    "REMOTE_XRAY_MANAGEMENT_SCRIPT",
    "SshXrayManagementTransport",
    "manage_xray",
    "REMOTE_XRAY_CONNECTION_UPDATE_SCRIPT",
    "SshXrayConnectionUpdateTransport",
    "validate_connection_settings",
    "update_xray_connection",
    "Hysteria2ManagementStatus",
    "REMOTE_HYSTERIA2_MANAGEMENT_SCRIPT",
    "SshHysteria2ManagementTransport",
    "manage_hysteria2",
    "MieruManagementStatus",
    "REMOTE_MIERU_MANAGEMENT_SCRIPT",
    "SshMieruManagementTransport",
    "manage_mieru",
    "validate_mieru_port",
    "REMOTE_MIERU_PORT_UPDATE_SCRIPT",
    "SshMieruPortUpdateTransport",
    "REMOTE_HYSTERIA2_CONNECTION_UPDATE_SCRIPT",
    "SshHysteria2ConnectionUpdateTransport",
    "update_hysteria2_connection",
    "update_mieru_port",
)
